// Code generated by Kitex v0.16.3. DO NOT EDIT.

package gatewayservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	streamcall "github.com/cloudwego/kitex/client/callopt/streamcall"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	transport "github.com/cloudwego/kitex/transport"
	v1 "github.com/sanbei101/im/kitex_gen/im/v1"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Connect(ctx context.Context, callOptions ...streamcall.Option) (stream GatewayService_ConnectClient, err error)
}

type GatewayService_ConnectClient streaming.BidiStreamingClient[v1.GatewayFrame, v1.APIFrame]

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, client.WithTransportProtocol(transport.GRPC))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kGatewayServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kGatewayServiceClient struct {
	*kClient
}

func (p *kGatewayServiceClient) Connect(ctx context.Context, callOptions ...streamcall.Option) (stream GatewayService_ConnectClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, streamcall.GetCallOptions(callOptions))
	return p.kClient.Connect(ctx)
}
