// Code generated by Kitex v0.12.4. DO NOT EDIT.

package gatewayservice

import (
	"context"
	"errors"
	"fmt"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	v1 "github.com/sanbei101/im/kitex_gen/im/v1"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Connect": kitex.NewMethodInfo(
		connectHandler,
		newConnectArgs,
		newConnectResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingBidirectional),
	),
}

var (
	gatewayServiceServiceInfo                = NewServiceInfo()
	gatewayServiceServiceInfoForClient       = NewServiceInfoForClient()
	gatewayServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return gatewayServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return gatewayServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return gatewayServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(true, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "GatewayService"
	handlerType := (*v1.GatewayService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "im.v1",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.12.4",
		Extra:           extra,
	}
	return svcInfo
}

func connectHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	streamingArgs, ok := arg.(*streaming.Args)
	if !ok {
		return errInvalidMessageType
	}
	st := streamingArgs.Stream
	stream := &gatewayServiceConnectServer{st}
	return handler.(v1.GatewayService).Connect(stream)
}

type gatewayServiceConnectClient struct {
	streaming.Stream
}

func (x *gatewayServiceConnectClient) DoFinish(err error) {
	if finisher, ok := x.Stream.(streaming.WithDoFinish); ok {
		finisher.DoFinish(err)
	} else {
		panic(fmt.Sprintf("streaming.WithDoFinish is not implemented by %T", x.Stream))
	}
}
func (x *gatewayServiceConnectClient) Send(m *v1.GatewayFrame) error {
	return x.Stream.SendMsg(m)
}
func (x *gatewayServiceConnectClient) Recv() (*v1.APIFrame, error) {
	m := new(v1.APIFrame)
	return m, x.Stream.RecvMsg(m)
}

type gatewayServiceConnectServer struct {
	streaming.Stream
}

func (x *gatewayServiceConnectServer) Send(m *v1.APIFrame) error {
	return x.Stream.SendMsg(m)
}

func (x *gatewayServiceConnectServer) Recv() (*v1.GatewayFrame, error) {
	m := new(v1.GatewayFrame)
	return m, x.Stream.RecvMsg(m)
}

func newConnectArgs() interface{} {
	return &ConnectArgs{}
}

func newConnectResult() interface{} {
	return &ConnectResult{}
}

type ConnectArgs struct {
	Req *v1.GatewayFrame
}

func (p *ConnectArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(v1.GatewayFrame)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ConnectArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ConnectArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ConnectArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ConnectArgs) Unmarshal(in []byte) error {
	msg := new(v1.GatewayFrame)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ConnectArgs_Req_DEFAULT *v1.GatewayFrame

func (p *ConnectArgs) GetReq() *v1.GatewayFrame {
	if !p.IsSetReq() {
		return ConnectArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ConnectArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ConnectArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ConnectResult struct {
	Success *v1.APIFrame
}

var ConnectResult_Success_DEFAULT *v1.APIFrame

func (p *ConnectResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(v1.APIFrame)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ConnectResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ConnectResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ConnectResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ConnectResult) Unmarshal(in []byte) error {
	msg := new(v1.APIFrame)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ConnectResult) GetSuccess() *v1.APIFrame {
	if !p.IsSetSuccess() {
		return ConnectResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ConnectResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.APIFrame)
}

func (p *ConnectResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ConnectResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Connect(ctx context.Context) (GatewayService_ConnectClient, error) {
	streamClient, ok := p.c.(client.Streaming)
	if !ok {
		return nil, fmt.Errorf("client not support streaming")
	}
	res := new(streaming.Result)
	err := streamClient.Stream(ctx, "Connect", nil, res)
	if err != nil {
		return nil, err
	}
	stream := &gatewayServiceConnectClient{res.Stream}
	return stream, nil
}
