// Code generated by Kitex v0.12.4. DO NOT EDIT.
package gatewayservice

import (
	server "github.com/cloudwego/kitex/server"
	v1 "github.com/sanbei101/im/kitex_gen/im/v1"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler v1.GatewayService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler v1.GatewayService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
