// Code generated by Kitex v0.16.3. DO NOT EDIT.
package gatewayservice

import (
	server "github.com/cloudwego/kitex/server"
	imv1 "github.com/sanbei101/im/kitex_gen/im/v1"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler imv1.GatewayService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler imv1.GatewayService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
