// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package imv1

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *GatewayFrame) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_GatewayFrame[number], err)
}

func (x *GatewayFrame) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var ov GatewayFrame_Hello
	x.Body = &ov
	var v Hello
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	ov.Hello = &v
	return offset, nil
}

func (x *GatewayFrame) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	var ov GatewayFrame_SendBatch
	x.Body = &ov
	var v SendBatch
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	ov.SendBatch = &v
	return offset, nil
}

func (x *GatewayFrame) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	var ov GatewayFrame_SessionBatch
	x.Body = &ov
	var v SessionBatch
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	ov.SessionBatch = &v
	return offset, nil
}

func (x *GatewayFrame) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	var ov GatewayFrame_ReceiptBatch
	x.Body = &ov
	var v ReceiptBatch
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	ov.ReceiptBatch = &v
	return offset, nil
}

func (x *GatewayFrame) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	var ov GatewayFrame_Heartbeat
	x.Body = &ov
	var v Heartbeat
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	ov.Heartbeat = &v
	return offset, nil
}

func (x *APIFrame) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_APIFrame[number], err)
}

func (x *APIFrame) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var ov APIFrame_HelloAck
	x.Body = &ov
	var v HelloAck
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	ov.HelloAck = &v
	return offset, nil
}

func (x *APIFrame) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	var ov APIFrame_SendResultBatch
	x.Body = &ov
	var v SendResultBatch
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	ov.SendResultBatch = &v
	return offset, nil
}

func (x *APIFrame) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	var ov APIFrame_PushBatch
	x.Body = &ov
	var v PushBatch
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	ov.PushBatch = &v
	return offset, nil
}

func (x *APIFrame) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	var ov APIFrame_RoutingError
	x.Body = &ov
	var v RoutingError
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	ov.RoutingError = &v
	return offset, nil
}

func (x *APIFrame) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	var ov APIFrame_Heartbeat
	x.Body = &ov
	var v Heartbeat
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	ov.Heartbeat = &v
	return offset, nil
}

func (x *Hello) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_Hello[number], err)
}

func (x *Hello) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.GatewayId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *Hello) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.TopologyVersion, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *HelloAck) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_HelloAck[number], err)
}

func (x *HelloAck) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.NodeId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *HelloAck) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.TopologyVersion, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SendBatch) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_SendBatch[number], err)
}

func (x *SendBatch) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.BatchId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SendBatch) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	var v SendMessage
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.Messages = append(x.Messages, &v)
	return offset, nil
}

func (x *SendMessage) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 6:
		offset, err = x.fastReadField6(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 7:
		offset, err = x.fastReadField7(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 8:
		offset, err = x.fastReadField8(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_SendMessage[number], err)
}

func (x *SendMessage) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.RequestId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SendMessage) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.ClientMsgId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SendMessage) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.SenderId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SendMessage) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.RoomId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SendMessage) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	x.MsgType, offset, err = fastpb.ReadInt32(buf, _type)
	return offset, err
}

func (x *SendMessage) fastReadField6(buf []byte, _type int8) (offset int, err error) {
	x.Payload, offset, err = fastpb.ReadBytes(buf, _type)
	return offset, err
}

func (x *SendMessage) fastReadField7(buf []byte, _type int8) (offset int, err error) {
	x.ReplyToMsgId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SendMessage) fastReadField8(buf []byte, _type int8) (offset int, err error) {
	x.Ext, offset, err = fastpb.ReadBytes(buf, _type)
	return offset, err
}

func (x *SendResultBatch) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_SendResultBatch[number], err)
}

func (x *SendResultBatch) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.BatchId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SendResultBatch) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	var v SendResult
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.Results = append(x.Results, &v)
	return offset, nil
}

func (x *SendResult) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 6:
		offset, err = x.fastReadField6(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 7:
		offset, err = x.fastReadField7(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 8:
		offset, err = x.fastReadField8(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_SendResult[number], err)
}

func (x *SendResult) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.RequestId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SendResult) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.ClientMsgId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SendResult) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.MsgId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SendResult) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.RoomId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SendResult) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	x.RoomSeq, offset, err = fastpb.ReadUint64(buf, _type)
	return offset, err
}

func (x *SendResult) fastReadField6(buf []byte, _type int8) (offset int, err error) {
	x.ServerTime, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *SendResult) fastReadField7(buf []byte, _type int8) (offset int, err error) {
	x.Code, offset, err = fastpb.ReadInt32(buf, _type)
	return offset, err
}

func (x *SendResult) fastReadField8(buf []byte, _type int8) (offset int, err error) {
	x.Error, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SessionBatch) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_SessionBatch[number], err)
}

func (x *SessionBatch) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v Session
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.Sessions = append(x.Sessions, &v)
	return offset, nil
}

func (x *Session) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_Session[number], err)
}

func (x *Session) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.SessionId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *Session) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.UserId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *Session) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.Online, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *ReceiptBatch) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ReceiptBatch[number], err)
}

func (x *ReceiptBatch) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v Receipt
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.Receipts = append(x.Receipts, &v)
	return offset, nil
}

func (x *Receipt) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_Receipt[number], err)
}

func (x *Receipt) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.UserId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *Receipt) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.RoomId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *Receipt) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.RoomSeq, offset, err = fastpb.ReadUint64(buf, _type)
	return offset, err
}

func (x *PushBatch) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_PushBatch[number], err)
}

func (x *PushBatch) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v Push
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.Pushes = append(x.Pushes, &v)
	return offset, nil
}

func (x *Push) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 6:
		offset, err = x.fastReadField6(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 7:
		offset, err = x.fastReadField7(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 8:
		offset, err = x.fastReadField8(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 9:
		offset, err = x.fastReadField9(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_Push[number], err)
}

func (x *Push) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.UserId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *Push) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.RoomId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *Push) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.RoomSeq, offset, err = fastpb.ReadUint64(buf, _type)
	return offset, err
}

func (x *Push) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.MsgId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *Push) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	x.SenderId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *Push) fastReadField6(buf []byte, _type int8) (offset int, err error) {
	x.MsgType, offset, err = fastpb.ReadInt32(buf, _type)
	return offset, err
}

func (x *Push) fastReadField7(buf []byte, _type int8) (offset int, err error) {
	x.Payload, offset, err = fastpb.ReadBytes(buf, _type)
	return offset, err
}

func (x *Push) fastReadField8(buf []byte, _type int8) (offset int, err error) {
	x.ServerTime, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *Push) fastReadField9(buf []byte, _type int8) (offset int, err error) {
	x.Ext, offset, err = fastpb.ReadBytes(buf, _type)
	return offset, err
}

func (x *RoutingError) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_RoutingError[number], err)
}

func (x *RoutingError) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.RoomId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *RoutingError) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Owner, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *RoutingError) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.TopologyVersion, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *Heartbeat) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_Heartbeat[number], err)
}

func (x *Heartbeat) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.UnixMicro, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *GatewayFrame) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	return offset
}

func (x *GatewayFrame) fastWriteField1(buf []byte) (offset int) {
	if x.GetHello() == nil {
		return offset
	}
	offset += fastpb.WriteMessage(buf[offset:], 1, x.GetHello())
	return offset
}

func (x *GatewayFrame) fastWriteField2(buf []byte) (offset int) {
	if x.GetSendBatch() == nil {
		return offset
	}
	offset += fastpb.WriteMessage(buf[offset:], 2, x.GetSendBatch())
	return offset
}

func (x *GatewayFrame) fastWriteField3(buf []byte) (offset int) {
	if x.GetSessionBatch() == nil {
		return offset
	}
	offset += fastpb.WriteMessage(buf[offset:], 3, x.GetSessionBatch())
	return offset
}

func (x *GatewayFrame) fastWriteField4(buf []byte) (offset int) {
	if x.GetReceiptBatch() == nil {
		return offset
	}
	offset += fastpb.WriteMessage(buf[offset:], 4, x.GetReceiptBatch())
	return offset
}

func (x *GatewayFrame) fastWriteField5(buf []byte) (offset int) {
	if x.GetHeartbeat() == nil {
		return offset
	}
	offset += fastpb.WriteMessage(buf[offset:], 5, x.GetHeartbeat())
	return offset
}

func (x *APIFrame) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	return offset
}

func (x *APIFrame) fastWriteField1(buf []byte) (offset int) {
	if x.GetHelloAck() == nil {
		return offset
	}
	offset += fastpb.WriteMessage(buf[offset:], 1, x.GetHelloAck())
	return offset
}

func (x *APIFrame) fastWriteField2(buf []byte) (offset int) {
	if x.GetSendResultBatch() == nil {
		return offset
	}
	offset += fastpb.WriteMessage(buf[offset:], 2, x.GetSendResultBatch())
	return offset
}

func (x *APIFrame) fastWriteField3(buf []byte) (offset int) {
	if x.GetPushBatch() == nil {
		return offset
	}
	offset += fastpb.WriteMessage(buf[offset:], 3, x.GetPushBatch())
	return offset
}

func (x *APIFrame) fastWriteField4(buf []byte) (offset int) {
	if x.GetRoutingError() == nil {
		return offset
	}
	offset += fastpb.WriteMessage(buf[offset:], 4, x.GetRoutingError())
	return offset
}

func (x *APIFrame) fastWriteField5(buf []byte) (offset int) {
	if x.GetHeartbeat() == nil {
		return offset
	}
	offset += fastpb.WriteMessage(buf[offset:], 5, x.GetHeartbeat())
	return offset
}

func (x *Hello) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *Hello) fastWriteField1(buf []byte) (offset int) {
	if x.GatewayId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetGatewayId())
	return offset
}

func (x *Hello) fastWriteField2(buf []byte) (offset int) {
	if x.TopologyVersion == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetTopologyVersion())
	return offset
}

func (x *HelloAck) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *HelloAck) fastWriteField1(buf []byte) (offset int) {
	if x.NodeId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetNodeId())
	return offset
}

func (x *HelloAck) fastWriteField2(buf []byte) (offset int) {
	if x.TopologyVersion == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetTopologyVersion())
	return offset
}

func (x *SendBatch) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *SendBatch) fastWriteField1(buf []byte) (offset int) {
	if x.BatchId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetBatchId())
	return offset
}

func (x *SendBatch) fastWriteField2(buf []byte) (offset int) {
	if x.Messages == nil {
		return offset
	}
	for i := range x.GetMessages() {
		offset += fastpb.WriteMessage(buf[offset:], 2, x.GetMessages()[i])
	}
	return offset
}

func (x *SendMessage) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	offset += x.fastWriteField6(buf[offset:])
	offset += x.fastWriteField7(buf[offset:])
	offset += x.fastWriteField8(buf[offset:])
	return offset
}

func (x *SendMessage) fastWriteField1(buf []byte) (offset int) {
	if x.RequestId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetRequestId())
	return offset
}

func (x *SendMessage) fastWriteField2(buf []byte) (offset int) {
	if x.ClientMsgId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetClientMsgId())
	return offset
}

func (x *SendMessage) fastWriteField3(buf []byte) (offset int) {
	if x.SenderId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetSenderId())
	return offset
}

func (x *SendMessage) fastWriteField4(buf []byte) (offset int) {
	if x.RoomId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 4, x.GetRoomId())
	return offset
}

func (x *SendMessage) fastWriteField5(buf []byte) (offset int) {
	if x.MsgType == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 5, x.GetMsgType())
	return offset
}

func (x *SendMessage) fastWriteField6(buf []byte) (offset int) {
	if len(x.Payload) == 0 {
		return offset
	}
	offset += fastpb.WriteBytes(buf[offset:], 6, x.GetPayload())
	return offset
}

func (x *SendMessage) fastWriteField7(buf []byte) (offset int) {
	if x.ReplyToMsgId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 7, x.GetReplyToMsgId())
	return offset
}

func (x *SendMessage) fastWriteField8(buf []byte) (offset int) {
	if len(x.Ext) == 0 {
		return offset
	}
	offset += fastpb.WriteBytes(buf[offset:], 8, x.GetExt())
	return offset
}

func (x *SendResultBatch) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *SendResultBatch) fastWriteField1(buf []byte) (offset int) {
	if x.BatchId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetBatchId())
	return offset
}

func (x *SendResultBatch) fastWriteField2(buf []byte) (offset int) {
	if x.Results == nil {
		return offset
	}
	for i := range x.GetResults() {
		offset += fastpb.WriteMessage(buf[offset:], 2, x.GetResults()[i])
	}
	return offset
}

func (x *SendResult) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	offset += x.fastWriteField6(buf[offset:])
	offset += x.fastWriteField7(buf[offset:])
	offset += x.fastWriteField8(buf[offset:])
	return offset
}

func (x *SendResult) fastWriteField1(buf []byte) (offset int) {
	if x.RequestId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetRequestId())
	return offset
}

func (x *SendResult) fastWriteField2(buf []byte) (offset int) {
	if x.ClientMsgId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetClientMsgId())
	return offset
}

func (x *SendResult) fastWriteField3(buf []byte) (offset int) {
	if x.MsgId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetMsgId())
	return offset
}

func (x *SendResult) fastWriteField4(buf []byte) (offset int) {
	if x.RoomId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 4, x.GetRoomId())
	return offset
}

func (x *SendResult) fastWriteField5(buf []byte) (offset int) {
	if x.RoomSeq == 0 {
		return offset
	}
	offset += fastpb.WriteUint64(buf[offset:], 5, x.GetRoomSeq())
	return offset
}

func (x *SendResult) fastWriteField6(buf []byte) (offset int) {
	if x.ServerTime == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 6, x.GetServerTime())
	return offset
}

func (x *SendResult) fastWriteField7(buf []byte) (offset int) {
	if x.Code == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 7, x.GetCode())
	return offset
}

func (x *SendResult) fastWriteField8(buf []byte) (offset int) {
	if x.Error == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 8, x.GetError())
	return offset
}

func (x *SessionBatch) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *SessionBatch) fastWriteField1(buf []byte) (offset int) {
	if x.Sessions == nil {
		return offset
	}
	for i := range x.GetSessions() {
		offset += fastpb.WriteMessage(buf[offset:], 1, x.GetSessions()[i])
	}
	return offset
}

func (x *Session) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *Session) fastWriteField1(buf []byte) (offset int) {
	if x.SessionId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetSessionId())
	return offset
}

func (x *Session) fastWriteField2(buf []byte) (offset int) {
	if x.UserId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetUserId())
	return offset
}

func (x *Session) fastWriteField3(buf []byte) (offset int) {
	if !x.Online {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 3, x.GetOnline())
	return offset
}

func (x *ReceiptBatch) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *ReceiptBatch) fastWriteField1(buf []byte) (offset int) {
	if x.Receipts == nil {
		return offset
	}
	for i := range x.GetReceipts() {
		offset += fastpb.WriteMessage(buf[offset:], 1, x.GetReceipts()[i])
	}
	return offset
}

func (x *Receipt) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *Receipt) fastWriteField1(buf []byte) (offset int) {
	if x.UserId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetUserId())
	return offset
}

func (x *Receipt) fastWriteField2(buf []byte) (offset int) {
	if x.RoomId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetRoomId())
	return offset
}

func (x *Receipt) fastWriteField3(buf []byte) (offset int) {
	if x.RoomSeq == 0 {
		return offset
	}
	offset += fastpb.WriteUint64(buf[offset:], 3, x.GetRoomSeq())
	return offset
}

func (x *PushBatch) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *PushBatch) fastWriteField1(buf []byte) (offset int) {
	if x.Pushes == nil {
		return offset
	}
	for i := range x.GetPushes() {
		offset += fastpb.WriteMessage(buf[offset:], 1, x.GetPushes()[i])
	}
	return offset
}

func (x *Push) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	offset += x.fastWriteField6(buf[offset:])
	offset += x.fastWriteField7(buf[offset:])
	offset += x.fastWriteField8(buf[offset:])
	offset += x.fastWriteField9(buf[offset:])
	return offset
}

func (x *Push) fastWriteField1(buf []byte) (offset int) {
	if x.UserId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetUserId())
	return offset
}

func (x *Push) fastWriteField2(buf []byte) (offset int) {
	if x.RoomId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetRoomId())
	return offset
}

func (x *Push) fastWriteField3(buf []byte) (offset int) {
	if x.RoomSeq == 0 {
		return offset
	}
	offset += fastpb.WriteUint64(buf[offset:], 3, x.GetRoomSeq())
	return offset
}

func (x *Push) fastWriteField4(buf []byte) (offset int) {
	if x.MsgId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 4, x.GetMsgId())
	return offset
}

func (x *Push) fastWriteField5(buf []byte) (offset int) {
	if x.SenderId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 5, x.GetSenderId())
	return offset
}

func (x *Push) fastWriteField6(buf []byte) (offset int) {
	if x.MsgType == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 6, x.GetMsgType())
	return offset
}

func (x *Push) fastWriteField7(buf []byte) (offset int) {
	if len(x.Payload) == 0 {
		return offset
	}
	offset += fastpb.WriteBytes(buf[offset:], 7, x.GetPayload())
	return offset
}

func (x *Push) fastWriteField8(buf []byte) (offset int) {
	if x.ServerTime == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 8, x.GetServerTime())
	return offset
}

func (x *Push) fastWriteField9(buf []byte) (offset int) {
	if len(x.Ext) == 0 {
		return offset
	}
	offset += fastpb.WriteBytes(buf[offset:], 9, x.GetExt())
	return offset
}

func (x *RoutingError) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *RoutingError) fastWriteField1(buf []byte) (offset int) {
	if x.RoomId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetRoomId())
	return offset
}

func (x *RoutingError) fastWriteField2(buf []byte) (offset int) {
	if x.Owner == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetOwner())
	return offset
}

func (x *RoutingError) fastWriteField3(buf []byte) (offset int) {
	if x.TopologyVersion == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetTopologyVersion())
	return offset
}

func (x *Heartbeat) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *Heartbeat) fastWriteField1(buf []byte) (offset int) {
	if x.UnixMicro == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetUnixMicro())
	return offset
}

func (x *GatewayFrame) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	return n
}

func (x *GatewayFrame) sizeField1() (n int) {
	if x.GetHello() == nil {
		return n
	}
	n += fastpb.SizeMessage(1, x.GetHello())
	return n
}

func (x *GatewayFrame) sizeField2() (n int) {
	if x.GetSendBatch() == nil {
		return n
	}
	n += fastpb.SizeMessage(2, x.GetSendBatch())
	return n
}

func (x *GatewayFrame) sizeField3() (n int) {
	if x.GetSessionBatch() == nil {
		return n
	}
	n += fastpb.SizeMessage(3, x.GetSessionBatch())
	return n
}

func (x *GatewayFrame) sizeField4() (n int) {
	if x.GetReceiptBatch() == nil {
		return n
	}
	n += fastpb.SizeMessage(4, x.GetReceiptBatch())
	return n
}

func (x *GatewayFrame) sizeField5() (n int) {
	if x.GetHeartbeat() == nil {
		return n
	}
	n += fastpb.SizeMessage(5, x.GetHeartbeat())
	return n
}

func (x *APIFrame) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	return n
}

func (x *APIFrame) sizeField1() (n int) {
	if x.GetHelloAck() == nil {
		return n
	}
	n += fastpb.SizeMessage(1, x.GetHelloAck())
	return n
}

func (x *APIFrame) sizeField2() (n int) {
	if x.GetSendResultBatch() == nil {
		return n
	}
	n += fastpb.SizeMessage(2, x.GetSendResultBatch())
	return n
}

func (x *APIFrame) sizeField3() (n int) {
	if x.GetPushBatch() == nil {
		return n
	}
	n += fastpb.SizeMessage(3, x.GetPushBatch())
	return n
}

func (x *APIFrame) sizeField4() (n int) {
	if x.GetRoutingError() == nil {
		return n
	}
	n += fastpb.SizeMessage(4, x.GetRoutingError())
	return n
}

func (x *APIFrame) sizeField5() (n int) {
	if x.GetHeartbeat() == nil {
		return n
	}
	n += fastpb.SizeMessage(5, x.GetHeartbeat())
	return n
}

func (x *Hello) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *Hello) sizeField1() (n int) {
	if x.GatewayId == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetGatewayId())
	return n
}

func (x *Hello) sizeField2() (n int) {
	if x.TopologyVersion == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetTopologyVersion())
	return n
}

func (x *HelloAck) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *HelloAck) sizeField1() (n int) {
	if x.NodeId == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetNodeId())
	return n
}

func (x *HelloAck) sizeField2() (n int) {
	if x.TopologyVersion == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetTopologyVersion())
	return n
}

func (x *SendBatch) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *SendBatch) sizeField1() (n int) {
	if x.BatchId == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetBatchId())
	return n
}

func (x *SendBatch) sizeField2() (n int) {
	if x.Messages == nil {
		return n
	}
	for i := range x.GetMessages() {
		n += fastpb.SizeMessage(2, x.GetMessages()[i])
	}
	return n
}

func (x *SendMessage) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	n += x.sizeField6()
	n += x.sizeField7()
	n += x.sizeField8()
	return n
}

func (x *SendMessage) sizeField1() (n int) {
	if x.RequestId == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetRequestId())
	return n
}

func (x *SendMessage) sizeField2() (n int) {
	if x.ClientMsgId == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetClientMsgId())
	return n
}

func (x *SendMessage) sizeField3() (n int) {
	if x.SenderId == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetSenderId())
	return n
}

func (x *SendMessage) sizeField4() (n int) {
	if x.RoomId == "" {
		return n
	}
	n += fastpb.SizeString(4, x.GetRoomId())
	return n
}

func (x *SendMessage) sizeField5() (n int) {
	if x.MsgType == 0 {
		return n
	}
	n += fastpb.SizeInt32(5, x.GetMsgType())
	return n
}

func (x *SendMessage) sizeField6() (n int) {
	if len(x.Payload) == 0 {
		return n
	}
	n += fastpb.SizeBytes(6, x.GetPayload())
	return n
}

func (x *SendMessage) sizeField7() (n int) {
	if x.ReplyToMsgId == "" {
		return n
	}
	n += fastpb.SizeString(7, x.GetReplyToMsgId())
	return n
}

func (x *SendMessage) sizeField8() (n int) {
	if len(x.Ext) == 0 {
		return n
	}
	n += fastpb.SizeBytes(8, x.GetExt())
	return n
}

func (x *SendResultBatch) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *SendResultBatch) sizeField1() (n int) {
	if x.BatchId == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetBatchId())
	return n
}

func (x *SendResultBatch) sizeField2() (n int) {
	if x.Results == nil {
		return n
	}
	for i := range x.GetResults() {
		n += fastpb.SizeMessage(2, x.GetResults()[i])
	}
	return n
}

func (x *SendResult) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	n += x.sizeField6()
	n += x.sizeField7()
	n += x.sizeField8()
	return n
}

func (x *SendResult) sizeField1() (n int) {
	if x.RequestId == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetRequestId())
	return n
}

func (x *SendResult) sizeField2() (n int) {
	if x.ClientMsgId == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetClientMsgId())
	return n
}

func (x *SendResult) sizeField3() (n int) {
	if x.MsgId == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetMsgId())
	return n
}

func (x *SendResult) sizeField4() (n int) {
	if x.RoomId == "" {
		return n
	}
	n += fastpb.SizeString(4, x.GetRoomId())
	return n
}

func (x *SendResult) sizeField5() (n int) {
	if x.RoomSeq == 0 {
		return n
	}
	n += fastpb.SizeUint64(5, x.GetRoomSeq())
	return n
}

func (x *SendResult) sizeField6() (n int) {
	if x.ServerTime == 0 {
		return n
	}
	n += fastpb.SizeInt64(6, x.GetServerTime())
	return n
}

func (x *SendResult) sizeField7() (n int) {
	if x.Code == 0 {
		return n
	}
	n += fastpb.SizeInt32(7, x.GetCode())
	return n
}

func (x *SendResult) sizeField8() (n int) {
	if x.Error == "" {
		return n
	}
	n += fastpb.SizeString(8, x.GetError())
	return n
}

func (x *SessionBatch) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *SessionBatch) sizeField1() (n int) {
	if x.Sessions == nil {
		return n
	}
	for i := range x.GetSessions() {
		n += fastpb.SizeMessage(1, x.GetSessions()[i])
	}
	return n
}

func (x *Session) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *Session) sizeField1() (n int) {
	if x.SessionId == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetSessionId())
	return n
}

func (x *Session) sizeField2() (n int) {
	if x.UserId == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetUserId())
	return n
}

func (x *Session) sizeField3() (n int) {
	if !x.Online {
		return n
	}
	n += fastpb.SizeBool(3, x.GetOnline())
	return n
}

func (x *ReceiptBatch) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *ReceiptBatch) sizeField1() (n int) {
	if x.Receipts == nil {
		return n
	}
	for i := range x.GetReceipts() {
		n += fastpb.SizeMessage(1, x.GetReceipts()[i])
	}
	return n
}

func (x *Receipt) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *Receipt) sizeField1() (n int) {
	if x.UserId == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetUserId())
	return n
}

func (x *Receipt) sizeField2() (n int) {
	if x.RoomId == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetRoomId())
	return n
}

func (x *Receipt) sizeField3() (n int) {
	if x.RoomSeq == 0 {
		return n
	}
	n += fastpb.SizeUint64(3, x.GetRoomSeq())
	return n
}

func (x *PushBatch) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *PushBatch) sizeField1() (n int) {
	if x.Pushes == nil {
		return n
	}
	for i := range x.GetPushes() {
		n += fastpb.SizeMessage(1, x.GetPushes()[i])
	}
	return n
}

func (x *Push) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	n += x.sizeField6()
	n += x.sizeField7()
	n += x.sizeField8()
	n += x.sizeField9()
	return n
}

func (x *Push) sizeField1() (n int) {
	if x.UserId == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetUserId())
	return n
}

func (x *Push) sizeField2() (n int) {
	if x.RoomId == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetRoomId())
	return n
}

func (x *Push) sizeField3() (n int) {
	if x.RoomSeq == 0 {
		return n
	}
	n += fastpb.SizeUint64(3, x.GetRoomSeq())
	return n
}

func (x *Push) sizeField4() (n int) {
	if x.MsgId == "" {
		return n
	}
	n += fastpb.SizeString(4, x.GetMsgId())
	return n
}

func (x *Push) sizeField5() (n int) {
	if x.SenderId == "" {
		return n
	}
	n += fastpb.SizeString(5, x.GetSenderId())
	return n
}

func (x *Push) sizeField6() (n int) {
	if x.MsgType == 0 {
		return n
	}
	n += fastpb.SizeInt32(6, x.GetMsgType())
	return n
}

func (x *Push) sizeField7() (n int) {
	if len(x.Payload) == 0 {
		return n
	}
	n += fastpb.SizeBytes(7, x.GetPayload())
	return n
}

func (x *Push) sizeField8() (n int) {
	if x.ServerTime == 0 {
		return n
	}
	n += fastpb.SizeInt64(8, x.GetServerTime())
	return n
}

func (x *Push) sizeField9() (n int) {
	if len(x.Ext) == 0 {
		return n
	}
	n += fastpb.SizeBytes(9, x.GetExt())
	return n
}

func (x *RoutingError) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *RoutingError) sizeField1() (n int) {
	if x.RoomId == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetRoomId())
	return n
}

func (x *RoutingError) sizeField2() (n int) {
	if x.Owner == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetOwner())
	return n
}

func (x *RoutingError) sizeField3() (n int) {
	if x.TopologyVersion == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetTopologyVersion())
	return n
}

func (x *Heartbeat) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *Heartbeat) sizeField1() (n int) {
	if x.UnixMicro == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetUnixMicro())
	return n
}

var fieldIDToName_GatewayFrame = map[int32]string{
	1: "Hello",
	2: "SendBatch",
	3: "SessionBatch",
	4: "ReceiptBatch",
	5: "Heartbeat",
}

var fieldIDToName_APIFrame = map[int32]string{
	1: "HelloAck",
	2: "SendResultBatch",
	3: "PushBatch",
	4: "RoutingError",
	5: "Heartbeat",
}

var fieldIDToName_Hello = map[int32]string{
	1: "GatewayId",
	2: "TopologyVersion",
}

var fieldIDToName_HelloAck = map[int32]string{
	1: "NodeId",
	2: "TopologyVersion",
}

var fieldIDToName_SendBatch = map[int32]string{
	1: "BatchId",
	2: "Messages",
}

var fieldIDToName_SendMessage = map[int32]string{
	1: "RequestId",
	2: "ClientMsgId",
	3: "SenderId",
	4: "RoomId",
	5: "MsgType",
	6: "Payload",
	7: "ReplyToMsgId",
	8: "Ext",
}

var fieldIDToName_SendResultBatch = map[int32]string{
	1: "BatchId",
	2: "Results",
}

var fieldIDToName_SendResult = map[int32]string{
	1: "RequestId",
	2: "ClientMsgId",
	3: "MsgId",
	4: "RoomId",
	5: "RoomSeq",
	6: "ServerTime",
	7: "Code",
	8: "Error",
}

var fieldIDToName_SessionBatch = map[int32]string{
	1: "Sessions",
}

var fieldIDToName_Session = map[int32]string{
	1: "SessionId",
	2: "UserId",
	3: "Online",
}

var fieldIDToName_ReceiptBatch = map[int32]string{
	1: "Receipts",
}

var fieldIDToName_Receipt = map[int32]string{
	1: "UserId",
	2: "RoomId",
	3: "RoomSeq",
}

var fieldIDToName_PushBatch = map[int32]string{
	1: "Pushes",
}

var fieldIDToName_Push = map[int32]string{
	1: "UserId",
	2: "RoomId",
	3: "RoomSeq",
	4: "MsgId",
	5: "SenderId",
	6: "MsgType",
	7: "Payload",
	8: "ServerTime",
	9: "Ext",
}

var fieldIDToName_RoutingError = map[int32]string{
	1: "RoomId",
	2: "Owner",
	3: "TopologyVersion",
}

var fieldIDToName_Heartbeat = map[int32]string{
	1: "UnixMicro",
}
