// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package db

import (
	"context"
	"errors"

	"encoding/json/jsontext"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const batchCreateMessages = `-- name: BatchCreateMessages :batchexec
INSERT INTO messages (
    msg_id,
    client_msg_id,
    sender_id,
    room_id,
    chat_type,
    msg_type,
    server_time,
    reply_to_msg_id,
    payload,
    ext
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
ON CONFLICT (msg_id) DO NOTHING
`

type BatchCreateMessagesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchCreateMessagesParams struct {
	MsgID        uuid.UUID      `json:"msg_id"`
	ClientMsgID  uuid.UUID      `json:"client_msg_id"`
	SenderID     uuid.UUID      `json:"sender_id"`
	RoomID       uuid.UUID      `json:"room_id"`
	ChatType     ChatType       `json:"chat_type"`
	MsgType      MessageType    `json:"msg_type"`
	ServerTime   int64          `json:"server_time"`
	ReplyToMsgID *uuid.UUID     `json:"reply_to_msg_id"`
	Payload      jsontext.Value `json:"payload"`
	Ext          jsontext.Value `json:"ext"`
}

func (q *Queries) BatchCreateMessages(ctx context.Context, arg []BatchCreateMessagesParams) *BatchCreateMessagesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.MsgID,
			a.ClientMsgID,
			a.SenderID,
			a.RoomID,
			a.ChatType,
			a.MsgType,
			a.ServerTime,
			a.ReplyToMsgID,
			a.Payload,
			a.Ext,
		}
		batch.Queue(batchCreateMessages, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchCreateMessagesBatchResults{br, len(arg), false}
}

func (b *BatchCreateMessagesBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchCreateMessagesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const batchCreateUsers = `-- name: BatchCreateUsers :batchone
INSERT INTO users (username, password)
VALUES ($1, $2)
RETURNING user_id
`

type BatchCreateUsersBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchCreateUsersParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

func (q *Queries) BatchCreateUsers(ctx context.Context, arg []BatchCreateUsersParams) *BatchCreateUsersBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Username,
			a.Password,
		}
		batch.Queue(batchCreateUsers, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchCreateUsersBatchResults{br, len(arg), false}
}

func (b *BatchCreateUsersBatchResults) QueryRow(f func(int, uuid.UUID, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var user_id uuid.UUID
		if b.closed {
			if f != nil {
				f(t, user_id, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(&user_id)
		if f != nil {
			f(t, user_id, err)
		}
	}
}

func (b *BatchCreateUsersBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
