// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const batchCreateRoom = `-- name: BatchCreateRoom :batchexec
INSERT INTO rooms (
    room_id, 
    chat_type, 
    name,
    avatar_url, 
    single_chat_hash
) VALUES (
    $1, 
    $2, 
    $3, 
    $4, 
    $5
)
`

type BatchCreateRoomBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchCreateRoomParams struct {
	RoomID         uuid.UUID `json:"room_id"`
	ChatType       ChatType  `json:"chat_type"`
	Name           string    `json:"name"`
	AvatarUrl      string    `json:"avatar_url"`
	SingleChatHash []byte    `json:"single_chat_hash"`
}

func (q *Queries) BatchCreateRoom(ctx context.Context, arg []BatchCreateRoomParams) *BatchCreateRoomBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.RoomID,
			a.ChatType,
			a.Name,
			a.AvatarUrl,
			a.SingleChatHash,
		}
		batch.Queue(batchCreateRoom, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchCreateRoomBatchResults{br, len(arg), false}
}

func (b *BatchCreateRoomBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchCreateRoomBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const batchCreateUser = `-- name: BatchCreateUser :batchexec
INSERT INTO users (
    user_id, 
    username, 
    password
) VALUES (
    $1, 
    $2, 
    $3
)
`

type BatchCreateUserBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchCreateUserParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Username string    `json:"username"`
	Password string    `json:"password"`
}

func (q *Queries) BatchCreateUser(ctx context.Context, arg []BatchCreateUserParams) *BatchCreateUserBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.UserID,
			a.Username,
			a.Password,
		}
		batch.Queue(batchCreateUser, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchCreateUserBatchResults{br, len(arg), false}
}

func (b *BatchCreateUserBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchCreateUserBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
