// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForBatchCopyMessages implements pgx.CopyFromSource.
type iteratorForBatchCopyMessages struct {
	rows                 []BatchCopyMessagesParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchCopyMessages) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchCopyMessages) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].MsgID,
		r.rows[0].ClientMsgID,
		r.rows[0].SenderID,
		r.rows[0].RoomID,
		r.rows[0].ChatType,
		r.rows[0].MsgType,
		r.rows[0].ServerTime,
		r.rows[0].ReplyToMsgID,
		r.rows[0].Payload,
		r.rows[0].Ext,
	}, nil
}

func (r iteratorForBatchCopyMessages) Err() error {
	return nil
}

func (q *Queries) BatchCopyMessages(ctx context.Context, arg []BatchCopyMessagesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"messages"}, []string{"msg_id", "client_msg_id", "sender_id", "room_id", "chat_type", "msg_type", "server_time", "reply_to_msg_id", "payload", "ext"}, &iteratorForBatchCopyMessages{rows: arg})
}
