// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message.sql

package db

import (
	"context"

	"encoding/json/jsontext"
	"github.com/google/uuid"
)

const addRoomMember = `-- name: AddRoomMember :exec
INSERT INTO room_members (room_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (room_id, user_id) DO NOTHING
`

type AddRoomMemberParams struct {
	RoomID uuid.UUID  `json:"room_id"`
	UserID uuid.UUID  `json:"user_id"`
	Role   MemberRole `json:"role"`
}

func (q *Queries) AddRoomMember(ctx context.Context, arg AddRoomMemberParams) error {
	_, err := q.db.Exec(ctx, addRoomMember, arg.RoomID, arg.UserID, arg.Role)
	return err
}

type BatchCopyMessagesParams struct {
	MsgID        uuid.UUID      `json:"msg_id"`
	ClientMsgID  uuid.UUID      `json:"client_msg_id"`
	SenderID     uuid.UUID      `json:"sender_id"`
	RoomID       uuid.UUID      `json:"room_id"`
	MsgType      MessageType    `json:"msg_type"`
	ServerTime   int64          `json:"server_time"`
	ReplyToMsgID *uuid.UUID     `json:"reply_to_msg_id"`
	Payload      jsontext.Value `json:"payload"`
	Ext          jsontext.Value `json:"ext"`
}

const createMessage = `-- name: CreateMessage :exec
INSERT INTO messages (
    msg_id,
    client_msg_id,
    sender_id,
    room_id,
    msg_type,
    server_time,
    reply_to_msg_id,
    payload,
    ext
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
`

type CreateMessageParams struct {
	MsgID        uuid.UUID      `json:"msg_id"`
	ClientMsgID  uuid.UUID      `json:"client_msg_id"`
	SenderID     uuid.UUID      `json:"sender_id"`
	RoomID       uuid.UUID      `json:"room_id"`
	MsgType      MessageType    `json:"msg_type"`
	ServerTime   int64          `json:"server_time"`
	ReplyToMsgID *uuid.UUID     `json:"reply_to_msg_id"`
	Payload      jsontext.Value `json:"payload"`
	Ext          jsontext.Value `json:"ext"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.Exec(ctx, createMessage,
		arg.MsgID,
		arg.ClientMsgID,
		arg.SenderID,
		arg.RoomID,
		arg.MsgType,
		arg.ServerTime,
		arg.ReplyToMsgID,
		arg.Payload,
		arg.Ext,
	)
	return err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (room_id, chat_type, name, avatar_url, single_chat_hash)
VALUES ($1, $2, $3, $4, $5)
RETURNING room_id
`

type CreateRoomParams struct {
	RoomID         uuid.UUID `json:"room_id"`
	ChatType       ChatType  `json:"chat_type"`
	Name           string    `json:"name"`
	AvatarUrl      string    `json:"avatar_url"`
	SingleChatHash []byte    `json:"single_chat_hash"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.RoomID,
		arg.ChatType,
		arg.Name,
		arg.AvatarUrl,
		arg.SingleChatHash,
	)
	var room_id uuid.UUID
	err := row.Scan(&room_id)
	return room_id, err
}

const getMembersByRoomIDs = `-- name: GetMembersByRoomIDs :many
SELECT room_id, user_id FROM room_members WHERE room_id = ANY($1::uuid[])
`

type GetMembersByRoomIDsRow struct {
	RoomID uuid.UUID `json:"room_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMembersByRoomIDs(ctx context.Context, roomIds []uuid.UUID) ([]*GetMembersByRoomIDsRow, error) {
	rows, err := q.db.Query(ctx, getMembersByRoomIDs, roomIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetMembersByRoomIDsRow{}
	for rows.Next() {
		var i GetMembersByRoomIDsRow
		if err := rows.Scan(&i.RoomID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT
    msg_id,
    client_msg_id,
    sender_id,
    room_id,
    msg_type,
    server_time,
    reply_to_msg_id,
    payload,
    ext
FROM messages
WHERE msg_id = $1
LIMIT 1
`

type GetMessageByIDRow struct {
	MsgID        uuid.UUID      `json:"msg_id"`
	ClientMsgID  uuid.UUID      `json:"client_msg_id"`
	SenderID     uuid.UUID      `json:"sender_id"`
	RoomID       uuid.UUID      `json:"room_id"`
	MsgType      MessageType    `json:"msg_type"`
	ServerTime   int64          `json:"server_time"`
	ReplyToMsgID *uuid.UUID     `json:"reply_to_msg_id"`
	Payload      jsontext.Value `json:"payload"`
	Ext          jsontext.Value `json:"ext"`
}

func (q *Queries) GetMessageByID(ctx context.Context, msgID uuid.UUID) (*GetMessageByIDRow, error) {
	row := q.db.QueryRow(ctx, getMessageByID, msgID)
	var i GetMessageByIDRow
	err := row.Scan(
		&i.MsgID,
		&i.ClientMsgID,
		&i.SenderID,
		&i.RoomID,
		&i.MsgType,
		&i.ServerTime,
		&i.ReplyToMsgID,
		&i.Payload,
		&i.Ext,
	)
	return &i, err
}

const getRoomByHash = `-- name: GetRoomByHash :one
SELECT room_id, chat_type, name, avatar_url, single_chat_hash, created_at, updated_at
FROM rooms
WHERE single_chat_hash = $1 AND chat_type = 'single'
LIMIT 1
`

func (q *Queries) GetRoomByHash(ctx context.Context, hash []byte) (*Room, error) {
	row := q.db.QueryRow(ctx, getRoomByHash, hash)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.ChatType,
		&i.Name,
		&i.AvatarUrl,
		&i.SingleChatHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getRoomMembers = `-- name: GetRoomMembers :many
SELECT user_id FROM room_members WHERE room_id = $1
`

func (q *Queries) GetRoomMembers(ctx context.Context, roomID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getRoomMembers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRooms = `-- name: GetUserRooms :many
SELECT room_id FROM room_members WHERE user_id = $1
`

func (q *Queries) GetUserRooms(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getUserRooms, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var room_id uuid.UUID
		if err := rows.Scan(&room_id); err != nil {
			return nil, err
		}
		items = append(items, room_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByRoom = `-- name: ListMessagesByRoom :many
SELECT
    msg_id,
    client_msg_id,
    sender_id,
    room_id,
    msg_type,
    server_time,
    reply_to_msg_id,
    payload,
    ext
FROM messages
WHERE room_id = $1
  AND server_time < $2
ORDER BY server_time DESC
LIMIT $3
`

type ListMessagesByRoomParams struct {
	RoomID           uuid.UUID `json:"room_id"`
	BeforeServerTime int64     `json:"before_server_time"`
	PageSize         int32     `json:"page_size"`
}

type ListMessagesByRoomRow struct {
	MsgID        uuid.UUID      `json:"msg_id"`
	ClientMsgID  uuid.UUID      `json:"client_msg_id"`
	SenderID     uuid.UUID      `json:"sender_id"`
	RoomID       uuid.UUID      `json:"room_id"`
	MsgType      MessageType    `json:"msg_type"`
	ServerTime   int64          `json:"server_time"`
	ReplyToMsgID *uuid.UUID     `json:"reply_to_msg_id"`
	Payload      jsontext.Value `json:"payload"`
	Ext          jsontext.Value `json:"ext"`
}

func (q *Queries) ListMessagesByRoom(ctx context.Context, arg ListMessagesByRoomParams) ([]*ListMessagesByRoomRow, error) {
	rows, err := q.db.Query(ctx, listMessagesByRoom, arg.RoomID, arg.BeforeServerTime, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListMessagesByRoomRow{}
	for rows.Next() {
		var i ListMessagesByRoomRow
		if err := rows.Scan(
			&i.MsgID,
			&i.ClientMsgID,
			&i.SenderID,
			&i.RoomID,
			&i.MsgType,
			&i.ServerTime,
			&i.ReplyToMsgID,
			&i.Payload,
			&i.Ext,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
