// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message.sql

package db

import (
	"context"

	"encoding/json/jsontext"
	"github.com/google/uuid"
)

type BatchCopyMessagesParams struct {
	MsgID        uuid.UUID      `json:"msg_id"`
	ClientMsgID  uuid.UUID      `json:"client_msg_id"`
	SenderID     uuid.UUID      `json:"sender_id"`
	RoomID       uuid.UUID      `json:"room_id"`
	MsgType      MessageType    `json:"msg_type"`
	ServerTime   int64          `json:"server_time"`
	ReplyToMsgID *uuid.UUID     `json:"reply_to_msg_id"`
	Payload      jsontext.Value `json:"payload"`
	Ext          jsontext.Value `json:"ext"`
}

const createMessage = `-- name: CreateMessage :exec
INSERT INTO messages (
    msg_id,
    client_msg_id,
    sender_id,
    room_id,
    msg_type,
    server_time,
    reply_to_msg_id,
    payload,
    ext
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
`

type CreateMessageParams struct {
	MsgID        uuid.UUID      `json:"msg_id"`
	ClientMsgID  uuid.UUID      `json:"client_msg_id"`
	SenderID     uuid.UUID      `json:"sender_id"`
	RoomID       uuid.UUID      `json:"room_id"`
	MsgType      MessageType    `json:"msg_type"`
	ServerTime   int64          `json:"server_time"`
	ReplyToMsgID *uuid.UUID     `json:"reply_to_msg_id"`
	Payload      jsontext.Value `json:"payload"`
	Ext          jsontext.Value `json:"ext"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.Exec(ctx, createMessage,
		arg.MsgID,
		arg.ClientMsgID,
		arg.SenderID,
		arg.RoomID,
		arg.MsgType,
		arg.ServerTime,
		arg.ReplyToMsgID,
		arg.Payload,
		arg.Ext,
	)
	return err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT
    msg_id,
    client_msg_id,
    sender_id,
    room_id,
    msg_type,
    server_time,
    reply_to_msg_id,
    payload,
    ext
FROM messages
WHERE msg_id = $1
LIMIT 1
`

type GetMessageByIDRow struct {
	MsgID        uuid.UUID      `json:"msg_id"`
	ClientMsgID  uuid.UUID      `json:"client_msg_id"`
	SenderID     uuid.UUID      `json:"sender_id"`
	RoomID       uuid.UUID      `json:"room_id"`
	MsgType      MessageType    `json:"msg_type"`
	ServerTime   int64          `json:"server_time"`
	ReplyToMsgID *uuid.UUID     `json:"reply_to_msg_id"`
	Payload      jsontext.Value `json:"payload"`
	Ext          jsontext.Value `json:"ext"`
}

func (q *Queries) GetMessageByID(ctx context.Context, msgID uuid.UUID) (*GetMessageByIDRow, error) {
	row := q.db.QueryRow(ctx, getMessageByID, msgID)
	var i GetMessageByIDRow
	err := row.Scan(
		&i.MsgID,
		&i.ClientMsgID,
		&i.SenderID,
		&i.RoomID,
		&i.MsgType,
		&i.ServerTime,
		&i.ReplyToMsgID,
		&i.Payload,
		&i.Ext,
	)
	return &i, err
}

const listMessagesByRoom = `-- name: ListMessagesByRoom :many
SELECT
    msg_id,
    client_msg_id,
    sender_id,
    room_id,
    msg_type,
    server_time,
    reply_to_msg_id,
    payload,
    ext
FROM messages
WHERE room_id = $1
  AND server_time < $2
ORDER BY server_time DESC
LIMIT $3
`

type ListMessagesByRoomParams struct {
	RoomID           uuid.UUID `json:"room_id"`
	BeforeServerTime int64     `json:"before_server_time"`
	PageSize         int32     `json:"page_size"`
}

type ListMessagesByRoomRow struct {
	MsgID        uuid.UUID      `json:"msg_id"`
	ClientMsgID  uuid.UUID      `json:"client_msg_id"`
	SenderID     uuid.UUID      `json:"sender_id"`
	RoomID       uuid.UUID      `json:"room_id"`
	MsgType      MessageType    `json:"msg_type"`
	ServerTime   int64          `json:"server_time"`
	ReplyToMsgID *uuid.UUID     `json:"reply_to_msg_id"`
	Payload      jsontext.Value `json:"payload"`
	Ext          jsontext.Value `json:"ext"`
}

func (q *Queries) ListMessagesByRoom(ctx context.Context, arg ListMessagesByRoomParams) ([]*ListMessagesByRoomRow, error) {
	rows, err := q.db.Query(ctx, listMessagesByRoom, arg.RoomID, arg.BeforeServerTime, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListMessagesByRoomRow{}
	for rows.Next() {
		var i ListMessagesByRoomRow
		if err := rows.Scan(
			&i.MsgID,
			&i.ClientMsgID,
			&i.SenderID,
			&i.RoomID,
			&i.MsgType,
			&i.ServerTime,
			&i.ReplyToMsgID,
			&i.Payload,
			&i.Ext,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
