// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: social.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addBlock = `-- name: AddBlock :exec
INSERT INTO blocks (blocker_id, blocked_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddBlockParams struct {
	BlockerID uuid.UUID `json:"blocker_id"`
	BlockedID uuid.UUID `json:"blocked_id"`
}

func (q *Queries) AddBlock(ctx context.Context, arg AddBlockParams) error {
	_, err := q.db.Exec(ctx, addBlock, arg.BlockerID, arg.BlockedID)
	return err
}

const areFriends = `-- name: AreFriends :one
SELECT EXISTS (
    SELECT 1 FROM friendships
    WHERE user_id_low = $1
      AND user_id_high = $2
)
`

type AreFriendsParams struct {
	UserIDLow  uuid.UUID `json:"user_id_low"`
	UserIDHigh uuid.UUID `json:"user_id_high"`
}

func (q *Queries) AreFriends(ctx context.Context, arg AreFriendsParams) (bool, error) {
	row := q.db.QueryRow(ctx, areFriends, arg.UserIDLow, arg.UserIDHigh)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createFriendship = `-- name: CreateFriendship :exec
INSERT INTO friendships (user_id_low, user_id_high)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type CreateFriendshipParams struct {
	UserIDLow  uuid.UUID `json:"user_id_low"`
	UserIDHigh uuid.UUID `json:"user_id_high"`
}

func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) error {
	_, err := q.db.Exec(ctx, createFriendship, arg.UserIDLow, arg.UserIDHigh)
	return err
}

const deleteBlock = `-- name: DeleteBlock :exec
DELETE FROM blocks
WHERE blocker_id = $1 AND blocked_id = $2
`

type DeleteBlockParams struct {
	BlockerID uuid.UUID `json:"blocker_id"`
	BlockedID uuid.UUID `json:"blocked_id"`
}

func (q *Queries) DeleteBlock(ctx context.Context, arg DeleteBlockParams) error {
	_, err := q.db.Exec(ctx, deleteBlock, arg.BlockerID, arg.BlockedID)
	return err
}

const deleteFriendship = `-- name: DeleteFriendship :exec
DELETE FROM friendships
WHERE user_id_low = $1
  AND user_id_high = $2
`

type DeleteFriendshipParams struct {
	UserIDLow  uuid.UUID `json:"user_id_low"`
	UserIDHigh uuid.UUID `json:"user_id_high"`
}

func (q *Queries) DeleteFriendship(ctx context.Context, arg DeleteFriendshipParams) error {
	_, err := q.db.Exec(ctx, deleteFriendship, arg.UserIDLow, arg.UserIDHigh)
	return err
}

const getFriendRequestForUpdate = `-- name: GetFriendRequestForUpdate :one
SELECT request_id, sender_id, receiver_id, status, created_at, updated_at
FROM friend_requests
WHERE request_id = $1
FOR UPDATE
`

func (q *Queries) GetFriendRequestForUpdate(ctx context.Context, requestID uuid.UUID) (*FriendRequest, error) {
	row := q.db.QueryRow(ctx, getFriendRequestForUpdate, requestID)
	var i FriendRequest
	err := row.Scan(
		&i.RequestID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const isBlockedBetween = `-- name: IsBlockedBetween :one
SELECT EXISTS (
    SELECT 1 FROM blocks
    WHERE (blocker_id = $1 AND blocked_id = $2)
       OR (blocker_id = $2 AND blocked_id = $1)
)
`

type IsBlockedBetweenParams struct {
	UserA uuid.UUID `json:"user_a"`
	UserB uuid.UUID `json:"user_b"`
}

func (q *Queries) IsBlockedBetween(ctx context.Context, arg IsBlockedBetweenParams) (bool, error) {
	row := q.db.QueryRow(ctx, isBlockedBetween, arg.UserA, arg.UserB)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listBlocks = `-- name: ListBlocks :many
SELECT u.user_id, u.username, u.display_name, u.avatar_url, u.bio
FROM blocks b
JOIN users u ON u.user_id = b.blocked_id
WHERE b.blocker_id = $1
ORDER BY b.created_at DESC
`

type ListBlocksRow struct {
	UserID      uuid.UUID `json:"user_id"`
	Username    string    `json:"username"`
	DisplayName string    `json:"display_name"`
	AvatarUrl   string    `json:"avatar_url"`
	Bio         string    `json:"bio"`
}

func (q *Queries) ListBlocks(ctx context.Context, blockerID uuid.UUID) ([]*ListBlocksRow, error) {
	rows, err := q.db.Query(ctx, listBlocks, blockerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListBlocksRow{}
	for rows.Next() {
		var i ListBlocksRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Bio,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFriends = `-- name: ListFriends :many
SELECT u.user_id, u.username, u.display_name, u.avatar_url, u.bio
FROM friendships f
JOIN users u ON u.user_id = CASE
    WHEN f.user_id_low = $1 THEN f.user_id_high
    ELSE f.user_id_low
END
WHERE f.user_id_low = $1 OR f.user_id_high = $1
ORDER BY u.username
`

type ListFriendsRow struct {
	UserID      uuid.UUID `json:"user_id"`
	Username    string    `json:"username"`
	DisplayName string    `json:"display_name"`
	AvatarUrl   string    `json:"avatar_url"`
	Bio         string    `json:"bio"`
}

func (q *Queries) ListFriends(ctx context.Context, userID uuid.UUID) ([]*ListFriendsRow, error) {
	rows, err := q.db.Query(ctx, listFriends, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListFriendsRow{}
	for rows.Next() {
		var i ListFriendsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Bio,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceivedFriendRequests = `-- name: ListReceivedFriendRequests :many
SELECT fr.request_id, fr.sender_id, fr.receiver_id, fr.status, fr.created_at,
       u.username, u.display_name, u.avatar_url, u.bio
FROM friend_requests fr
JOIN users u ON u.user_id = fr.sender_id
WHERE fr.receiver_id = $1 AND fr.status = 'pending'
ORDER BY fr.created_at DESC
`

type ListReceivedFriendRequestsRow struct {
	RequestID   uuid.UUID           `json:"request_id"`
	SenderID    uuid.UUID           `json:"sender_id"`
	ReceiverID  uuid.UUID           `json:"receiver_id"`
	Status      FriendRequestStatus `json:"status"`
	CreatedAt   time.Time           `json:"created_at"`
	Username    string              `json:"username"`
	DisplayName string              `json:"display_name"`
	AvatarUrl   string              `json:"avatar_url"`
	Bio         string              `json:"bio"`
}

func (q *Queries) ListReceivedFriendRequests(ctx context.Context, receiverID uuid.UUID) ([]*ListReceivedFriendRequestsRow, error) {
	rows, err := q.db.Query(ctx, listReceivedFriendRequests, receiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListReceivedFriendRequestsRow{}
	for rows.Next() {
		var i ListReceivedFriendRequestsRow
		if err := rows.Scan(
			&i.RequestID,
			&i.SenderID,
			&i.ReceiverID,
			&i.Status,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Bio,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFriendRequestStatus = `-- name: SetFriendRequestStatus :exec
UPDATE friend_requests
SET status = $1, updated_at = NOW()
WHERE request_id = $2
`

type SetFriendRequestStatusParams struct {
	Status    FriendRequestStatus `json:"status"`
	RequestID uuid.UUID           `json:"request_id"`
}

func (q *Queries) SetFriendRequestStatus(ctx context.Context, arg SetFriendRequestStatusParams) error {
	_, err := q.db.Exec(ctx, setFriendRequestStatus, arg.Status, arg.RequestID)
	return err
}

const upsertFriendRequest = `-- name: UpsertFriendRequest :one
INSERT INTO friend_requests (sender_id, receiver_id)
VALUES ($1, $2)
ON CONFLICT (sender_id, receiver_id) DO UPDATE
SET status = 'pending', updated_at = NOW()
RETURNING request_id, sender_id, receiver_id, status, created_at, updated_at
`

type UpsertFriendRequestParams struct {
	SenderID   uuid.UUID `json:"sender_id"`
	ReceiverID uuid.UUID `json:"receiver_id"`
}

func (q *Queries) UpsertFriendRequest(ctx context.Context, arg UpsertFriendRequestParams) (*FriendRequest, error) {
	row := q.db.QueryRow(ctx, upsertFriendRequest, arg.SenderID, arg.ReceiverID)
	var i FriendRequest
	err := row.Scan(
		&i.RequestID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
