// Code generated by Kitex v0.16.3. DO NOT EDIT.

package gatewayservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	pb "github.com/sanbei101/im/proto/pb"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Connect": kitex.NewMethodInfo(
		connectHandler,
		newConnectArgs,
		newConnectResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingBidirectional),
	),
}

var (
	gatewayServiceServiceInfo = NewServiceInfo()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return gatewayServiceServiceInfo
}

// NewServiceInfo creates a new ServiceInfo
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo()
}

func newServiceInfo() *kitex.ServiceInfo {
	serviceName := "GatewayService"
	handlerType := (*pb.GatewayService)(nil)
	extra := map[string]interface{}{
		"PackageName": "pb",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         serviceMethods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func connectHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	st, err := streaming.GetServerStreamFromArg(arg)
	if err != nil {
		return err
	}
	stream := streaming.NewBidiStreamingServer[pb.GatewayFrame, pb.APIFrame](st)
	return handler.(pb.GatewayService).Connect(ctx, stream)
}

func newConnectArgs() interface{} {
	return &ConnectArgs{}
}

func newConnectResult() interface{} {
	return &ConnectResult{}
}

type ConnectArgs struct {
	Req *pb.GatewayFrame
}

func (p *ConnectArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ConnectArgs) Unmarshal(in []byte) error {
	msg := new(pb.GatewayFrame)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ConnectArgs_Req_DEFAULT *pb.GatewayFrame

func (p *ConnectArgs) GetReq() *pb.GatewayFrame {
	if !p.IsSetReq() {
		return ConnectArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ConnectArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ConnectArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ConnectResult struct {
	Success *pb.APIFrame
}

var ConnectResult_Success_DEFAULT *pb.APIFrame

func (p *ConnectResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ConnectResult) Unmarshal(in []byte) error {
	msg := new(pb.APIFrame)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ConnectResult) GetSuccess() *pb.APIFrame {
	if !p.IsSetSuccess() {
		return ConnectResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ConnectResult) SetSuccess(x interface{}) {
	p.Success = x.(*pb.APIFrame)
}

func (p *ConnectResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ConnectResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c  client.Client
	sc client.Streaming
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c:  c,
		sc: c.(client.Streaming),
	}
}

func (p *kClient) Connect(ctx context.Context) (GatewayService_ConnectClient, error) {
	st, err := p.sc.StreamX(ctx, "Connect")
	if err != nil {
		return nil, err
	}
	stream := streaming.NewBidiStreamingClient[pb.GatewayFrame, pb.APIFrame](st)
	return stream, nil
}
