// Code generated by Kitex v0.16.3. DO NOT EDIT.
package gatewayservice

import (
	server "github.com/cloudwego/kitex/server"
	pb "github.com/sanbei101/im/proto/pb"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler pb.GatewayService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler pb.GatewayService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
